import Link from "next/link";

export const metadata = {
  title: "Thebes AI — Grow into AI-native talent",
  description:
    "A thinking diagnostic for the AI era. Reason through a math problem in English, turn your own words into a prompt, and watch AI build it into a program you can play and understand.",
};

/* ── SVG brand mark ────────────────────────────────────────── */
function BrandMark({ size = 26 }: { size?: number }) {
  return (
    <svg
      className="lp-brand-mark"
      width={size}
      height={size}
      viewBox="0 0 32 32"
      fill="none"
      aria-hidden="true"
    >
      <path
        d="M6 28 V14 a10 10 0 0 1 20 0 V28"
        stroke="#14110C"
        strokeWidth="2"
        strokeLinecap="round"
      />
      <path
        d="M11 28 V18 a5 5 0 0 1 10 0 V28"
        stroke="#B5411B"
        strokeWidth="2"
        strokeLinecap="round"
      />
      <circle cx="16" cy="11" r="1.6" fill="#B5411B" />
    </svg>
  );
}

const LOOP = [
  {
    n: "1",
    title: "Reason it out — in English",
    body: "Talk through one math problem in the language AI thinks in. Not the answer; how you frame it, break it down, and connect the pieces.",
  },
  {
    n: "2",
    title: "Your words become a prompt",
    body: "The whole conversation is distilled into one precise English paragraph — automatically. You didn't write a prompt. You were building one all along.",
  },
  {
    n: "3",
    title: "One tap, a real AI build",
    body: "Turn that prompt into an actual artifact — a playable game, a 60-second explainer, an adaptive quiz — generated by AI from your own reasoning.",
  },
  {
    n: "4",
    title: "Play what your mind made",
    body: "You experience your own thinking, made real. The concept finally clicks — and you've just done prompt-engineering, learned by doing.",
  },
];

export default function GlobalLanding() {
  return (
    <div
      className="lp-root"
      style={{ background: "var(--paper)", color: "var(--ink)", fontFamily: "var(--font-sans)" }}
    >
      {/* ── Nav ──────────────────────────────────────────────── */}
      <nav className="lp-nav">
        <div className="lp-nav-inner">
          <Link href="/en" className="lp-brand">
            <BrandMark />
            <span>Thebes</span>
            <span className="lp-brand-ai">AI</span>
          </Link>
          <div className="lp-nav-links">
            <a href="#loop">The loop</a>
            <a href="#how">How it works</a>
            <a href="#report">The report</a>
            <Link href="/">한국어</Link>
          </div>
          <Link href="/session/demo" className="lp-nav-cta">
            Start free
            <span style={{ fontFamily: "var(--font-mono)", fontSize: 11 }}>→</span>
          </Link>
        </div>
      </nav>

      {/* ── Hero ─────────────────────────────────────────────── */}
      <section className="lp-hero lp-section" style={{ padding: "88px 0 104px" }}>
        <div className="lp-container">
          <div className="lp-hero-eyebrow">
            <span className="dot" />
            <span>AI-native thinking · for the next generation</span>
          </div>
          <h1
            style={{
              fontSize: "clamp(27px, 3.6vw, 44px)",
              lineHeight: 1.18,
              maxWidth: "760px",
            }}
          >
            English is global.
            <br />
            Math is universal.
            <br />
            <span style={{ color: "var(--accent)" }}>
              Math in English is the universally global language.
            </span>
            <br />
            And AI requires it.
          </h1>
          <p className="hero-sub" style={{ marginTop: 24, maxWidth: 520 }}>
            A 5-minute diagnostic that turns your math reasoning into a real AI build — one
            you can play, and finally understand.
          </p>
          <div className="hero-cta lp-hero-cta">
            <Link href="/session/demo" className="lp-btn lp-btn-primary">
              Start the free diagnostic
              <span style={{ fontFamily: "var(--font-mono)" }}>→</span>
            </Link>
            <a className="lp-hero-secondary" href="#loop">
              See the loop
              <span style={{ fontFamily: "var(--font-mono)", fontSize: 11 }}>↓</span>
            </a>
          </div>
        </div>
      </section>

      {/* ── The shift (dark) ─────────────────────────────────── */}
      <section className="lp-counter lp-section">
        <div className="lp-container">
          <div className="lp-section-head" style={{ marginBottom: 0 }}>
            <div className="lp-eyebrow">
              <span className="dot" />
              The shift no one prepared you for
            </div>
            <h2 style={{ marginTop: 18 }}>
              Speed was the old game.
              <br />
              <span className="em">AI already won it.</span>
            </h2>
          </div>
          <div className="lp-counter-compare">
            <div className="lp-counter-col us">
              <div className="label">What Thebes builds</div>
              <div className="h">The reasoning AI can&apos;t replace</div>
              <p>
                Framing the problem, seeing how things connect, and directing AI to build on
                your thinking. That is the talent the AI era actually pays for.
              </p>
            </div>
            <div className="lp-counter-col them">
              <div className="label">What most schooling trains</div>
              <div className="h">Faster, more, fewer mistakes</div>
              <p>
                More problems, solved quicker, with no errors. But that is exactly what AI does
                in five seconds — for free.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ── The loop (the wow) ───────────────────────────────── */}
      <section className="lp-section lp-polya-bg" id="loop">
        <div className="lp-container">
          <div className="lp-section-head">
            <div className="lp-eyebrow">
              <span className="dot" />
              How you become AI-native
            </div>
            <h2>
              You don&apos;t just solve the problem.
              <br />
              You turn your thinking into a program.
            </h2>
            <p className="lede">
              Think → prompt → create → understand. This is the loop that grows AI-native
              talent — learned by doing it, not reading about it.
            </p>
          </div>
          <div
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(2, 1fr)",
              gap: 16,
              marginTop: 8,
            }}
            className="lp-loop-grid"
          >
            {LOOP.map((s) => (
              <div
                key={s.n}
                style={{
                  background: "var(--paper-2)",
                  border: "1px solid var(--line)",
                  borderRadius: "var(--radius)",
                  padding: "28px 26px",
                }}
              >
                <div
                  style={{
                    fontFamily: "var(--font-mono)",
                    fontSize: 28,
                    fontWeight: 600,
                    color: "var(--accent)",
                    lineHeight: 1,
                  }}
                >
                  {s.n}
                </div>
                <div
                  style={{
                    marginTop: 14,
                    fontSize: 18,
                    fontWeight: 600,
                    letterSpacing: "-0.01em",
                  }}
                >
                  {s.title}
                </div>
                <p
                  style={{
                    marginTop: 8,
                    fontSize: 14.5,
                    lineHeight: 1.6,
                    color: "var(--ink-2)",
                  }}
                >
                  {s.body}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── How it works (diagnostic) ────────────────────────── */}
      <section className="lp-section" id="how">
        <div className="lp-container">
          <div className="lp-section-head">
            <div className="lp-eyebrow">
              <span className="dot" />
              The diagnostic
            </div>
            <h2>
              We don&apos;t chase the answer.
              <br />
              We widen how you think.
            </h2>
            <p className="lede">
              Reframe → Components → Relationships → Relevance → Transfer. An AI coach walks
              these five steps with you, in English, every session — measuring not what you
              answer, but how you reason.
            </p>
          </div>
        </div>
      </section>

      {/* ── Why math, why English ────────────────────────────── */}
      <section className="lp-section" id="why">
        <div className="lp-container">
          <div className="lp-section-head">
            <div className="lp-eyebrow">
              <span className="dot" />
              Why math, why English
            </div>
            <h2>
              The most honest training ground,
              <br />
              in the language AI reasons in.
            </h2>
          </div>
          <div className="lp-two-grid">
            <div className="lp-acad-card">
              <div className="tag">The medium</div>
              <div className="subj">Math</div>
              <div className="what">
                <p style={{ margin: 0, fontSize: 14.5, lineHeight: 1.6, color: "var(--ink-2)" }}>
                  No opinions, no memorized essays — just whether your thinking holds. It is the
                  cleanest mirror of how a mind actually reasons.
                </p>
              </div>
            </div>
            <div className="lp-acad-card">
              <div className="tag">The language</div>
              <div className="subj">English</div>
              <div className="what">
                <p style={{ margin: 0, fontSize: 14.5, lineHeight: 1.6, color: "var(--ink-2)" }}>
                  Not a school subject anymore — the language AI thinks in. Learn to reason in
                  it, and you direct AI with precision instead of guesswork.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── The report ───────────────────────────────────────── */}
      <section className="lp-section lp-report-bg" id="report">
        <div className="lp-container">
          <div className="lp-section-head">
            <div className="lp-eyebrow">
              <span className="dot" />
              What you get back
            </div>
            <h2>
              Not a score.
              <br />
              A map of how you think.
            </h2>
            <p className="lede">
              We break the vague idea of &ldquo;thinking ability&rdquo; into six measurable
              constructs — reframing, decomposition, relational thinking, relevance, transfer,
              and English reasoning — and track them over time as your AI Talent Index.
            </p>
          </div>
        </div>
      </section>

      {/* ── Team ─────────────────────────────────────────────── */}
      <section className="lp-team lp-section" id="team">
        <div className="lp-container">
          <div className="lp-section-head">
            <div className="lp-eyebrow">
              <span className="dot" />
              The team
            </div>
            <h2>
              Built by people who
              <br />
              <span className="em">measure minds for a living.</span>
            </h2>
          </div>
          <div className="lp-team-grid lp-team-grid-3">
            <div className="lp-member">
              <div className="role">Mathematics</div>
              <div className="school">
                New York University
                <br />
                Department of Mathematics
              </div>
              <p>Owns the rigor of the reasoning and the accuracy of every problem.</p>
            </div>
            <div className="lp-member">
              <div className="role">Psychometrics</div>
              <div className="school">
                University of Minnesota
                <br />
                John Jay College
              </div>
              <p>Turns the fuzzy word &ldquo;thinking&rdquo; into something measurable.</p>
            </div>
            <div className="lp-member">
              <div className="role">Engineering</div>
              <div className="school">
                University of California, Davis
                <br />
                Computer Science (B.S.)
              </div>
              <p>Makes measurement and diagnosis into a product that actually works.</p>
            </div>
          </div>
          <blockquote className="lp-team-quote">
            &ldquo;A test can own the score. We own the{" "}
            <span style={{ color: "var(--accent-soft)" }}>thinking</span> the score can&apos;t
            see — and we show it as a diagnosis, not vague praise.&rdquo;
          </blockquote>
        </div>
      </section>

      {/* ── Closing CTA ──────────────────────────────────────── */}
      <section className="lp-closing">
        <div className="lp-container">
          <h2>
            The AI era won&apos;t reward the fastest calculator.
            <br />
            <span className="em">It rewards the clearest thinker.</span>
            <br />
            Start with one problem.
          </h2>
          <p className="sub">
            A free 5-minute diagnostic. Your own reasoning, turned into a real AI build.
            <br />
            This is where AI-native talent begins.
          </p>
          <div className="lp-hero-cta" style={{ justifyContent: "center", marginTop: 40 }}>
            <Link href="/session/demo" className="lp-btn lp-btn-primary">
              Start free
              <span style={{ fontFamily: "var(--font-mono)" }}>→</span>
            </Link>
            <a href="mailto:hello@thebes.ai" className="lp-btn lp-btn-ghost">
              Partner with us
            </a>
          </div>
        </div>
      </section>

      {/* ── Footer ───────────────────────────────────────────── */}
      <footer className="lp-footer">
        <div className="lp-container inner">
          <div>© 2026 Thebes AI · The thinking diagnostic for the AI era</div>
          <div style={{ display: "flex", gap: 18, flexWrap: "wrap" }}>
            <Link href="/methodology">Methodology</Link>
            <Link href="/connect">Developers</Link>
            <Link href="/">한국어</Link>
            <a href="mailto:hello@thebes.ai">Contact</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
